### PR TITLE
Helm chart: bump app version to v0.20.0

### PR DESCRIPTION
**Pull request by bmorton**
This bumps the app version to v0.20.0 and updates the `prepare-release` task in the `Makefile` to update the `appVersion` in the Helm chart.

### CODE REVIEW

**Comment by bmorton** [comment]
Ah-ha!  I missed the `make helm` target there before.  It looks like appVersion is all automated too so I pulled that out of `prepare-release`.  I think this should look more complete now!

**Comment by bmorton** [comment]
Alright -- I figured out that appVersion wasn't being updated and I ended up moving that to the `helm` target.  When I run `make helm` now, it seems like everything is packaged properly.

How does this look now?

**Comment by alexandrevilain** [comment]
It looks great ! 👍

**Review by alexandrevilain — APPROVED** [review]

**Comment by bmorton** [comment]
I went to pull down `v0.6.0`, but noticed that it wasn't available.  Is there another step to getting this published?

**Comment by ttretau** [comment]
Hi @bmorton ,
I think the chart release failed in the Github Action due to be failing with different GNU sed.
Adding #866 to fix this..

**Comment by ttretau** [comment]
We might need now to run [the workflow ](https://github.com/alexandrevilain/temporal-operator/actions/workflows/release-chart.yaml) manually, because there was no change in `charts/`.. @alexandrevilain 🙌

**Comment by alexandrevilain** [comment]
Charts is now released @bmorton :) 
See: https://github.com/alexandrevilain/temporal-operator/releases/tag/helm-chart-0.6.0

**Pull request merged**
