### PR TITLE
Add service labels / annotations overrides for UI

### PR DESCRIPTION
**Pull request by MichaelCombs28**
In GKE, services require annotations referencing a backendconfig/frontendconfig for ingress resources to work properly. This PR will add the ability to override the labels and annotations of the UI service resource.

### CODE REVIEW

**Review by alexandrevilain — CHANGES_REQUESTED** [review]
Hi @MichaelCombs28 ! 
Thanks for the proposal! The idea is great, and seems legit for the GKE use-case.
"Overrides" are available in the temporal-operator's API for edge cases which can't be part of the API.
So, IMO it shouldn't be be in the "override" part.

We can imagine the following spec:
```yaml
spec:
  ui:
    service:
       labels: {}
       annotations: {}
```

This would be easier to understand as it's already done for ingress, see: https://alexandrevilain.github.io/temporal-operator/api/v1beta1/#temporal.io/v1beta1.TemporalUIIngressSpec

**Comment by MichaelCombs28** [comment]
Sounds good to me, I'll move it.

**Review by alexandrevilain — APPROVED** [review]
LGTM! Thanks ! 🎉

**Comment by MichaelCombs28** [comment]
Good to merge? Also for cutting new versions, should I create a PR requesting a tag cut?

**Pull request merged**
