### PR TITLE
Updated ClusterServiceVersion for Operatorhub release v0.9.1

### PR DESCRIPTION
**Pull request by ktenzer**
Signed-off-by: ktenzer <keith.tenzer@gmail.com>

### CODE REVIEW

**Comment by alexandrevilain** [comment]
Hi! Thanks! 
Which command did you run ? I there any missing action in the Makefile ?

**Comment by ktenzer** [comment]
> 

No the command just generates a basic csv. You have to add API documentation of CRDs, description, image, lots of stuff. I did this manually. In this case most of it was fine we were just missing API doc of temporalworkerprocess CRD and some other minor changes.

**Comment by alexandrevilain** [comment]
Alright, thanks.
I restart e2e tests due to github rate limit errors and I'll merge asap :)

**Comment by ktenzer** [comment]
Awesome, can you check my last message via slack regarding local setup nil
pointers, trying to get dev environment working again and need some help :)

**Pull request merged**
