### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by Mysterious786**

### CODE REVIEW

**Comment by alexandrevilain** [comment]
Hi!

What's the goal of this PR ? Looks like a spam for hacktoberfest.
I signal it as SPAM.

**Comment by Mysterious786** [comment]
I thought of adding this for the new conributors,sorry for that pull request.

**Comment by Mysterious786** [comment]
My intention was not to spam .

**Comment by alexandrevilain** [comment]
Sorry but `git clone <git repo>` and `cd filename` is not helping anyone.

**Pull request closed without merging**
