### PR TITLE
Automate the operatorhub bundle creation

### PR DESCRIPTION
**Pull request by alexandrevilain**

### CODE REVIEW

**Comment by alexandrevilain** [comment]
Hi @ktenzer cloud you please have a look ?

**Review by ktenzer — COMMENTED** [review]
Looks good, I pulled PR and ran some live tests as well as built the bundle. Only thing I would change is to increment VERSION to 0.7.0 instead of keeping it at 0.6.2.

**Comment by alexandrevilain** [comment]
> Looks good, I pulled PR and ran some live tests as well as built the bundle. Only thing I would change is to increment VERSION to 0.7.0 instead of keeping it at 0.6.2.

Thanks for your review 👍
IMO We can't release v0.7.0 without finalizing API refactoring. I'm currenlty working on it, I hope to submit a PR soon 🙂

**Comment by alexandrevilain** [comment]
(Updating `VERSION` to `0.7.0`will be part of the `Release v0.7.0` PR)

**Comment by ElanHasson** [comment]
I saw this made it to release-- when will it be available on operator hub?

**Comment by ktenzer** [comment]
@ElanHasson I just pushed to operatorhub so it should be available soon (https://github.com/k8s-operatorhub/community-operators/pull/1793)

**Pull request merged**
