### PR TITLE
Support temporal 1.22.x

### LINKED ISSUE #502: Support temporal 1.22.x
Branch: https://github.com/temporalio/temporal/tree/release/v1.22.x
Tag: https://github.com/temporalio/temporal/releases/tag/v1.22.0

Not sure how much effort it takes to support a new minor version. If there is a brief developer guide, more contributors may help if needed.

### PR DESCRIPTION
**Pull request by yujunz**
Close #502

### CODE REVIEW

**Comment by yujunz** [comment]
Local build failing. It seems an issue in upstream dependency.

```
 # Build
  RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o manager main.go
...
  [builder 12/12] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go
       → # github.com/alexandrevilain/temporal-operator/api/v1beta1
       → api/v1beta1/temporalcluster_types.go:423:25: DatastoreType does not satisfy ~[]DatastoreType (DatastoreType missing in ~[]github.com/alexandrevilain/temporal-operator/api/v1beta1.DatastoreType)
       → api/v1beta1/temporalcluster_types.go:423:40: cannot use SQLDataStores (variable of type []DatastoreType) as DatastoreType value in argument to slices.Contains[DatastoreType]
       → # go.temporal.io/server/common/metrics
       → /go/pkg/mod/go.temporal.io/server@v1.22.0/common/metrics/opentelemetry_provider.go:78:18: cannot use aggregation.ExplicitBucketHistogram{…} (value of type aggregation.ExplicitBucketHistogram) as "go.opentelemetry.io/otel/sdk/metric".Aggregation value in struct literal: aggregation.ExplicitBucketHistogram does not implement "go.opentelemetry.io/otel/sdk/metric".Aggregation (missing method copy)
       → 		have Copy() aggregation.Aggregation
       → 		want copy() "go.opentelemetry.io/otel/sdk/metric".Aggregation
     
     ERROR IN: [builder 12/12] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go

Build Failed: ImageBuild: process "/bin/sh -c CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o manager main.go" did not complete successfully: exit code: 1
```

**Comment by yujunz** [comment]
Now panic in ConfigmapBuilder Update

```
2023-09-12T11:53:00Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "TemporalCluster": {"name":"prod","namespace":"demo"}, "namespace": "demo", "name": "prod", "reconcileID": "991561ff-5d4b-4c8f-bab3-91e8f3a17a92"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fcba21]

goroutine 325 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x22ef360, 0x4007690})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/alexandrevilain/temporal-operator/internal/resource/config.(*ConfigmapBuilder).Update(0xc0008c3820, {0x2c225a8?, 0xc000db7560})
	/workspace/internal/resource/config/configmap_builder.go:241 +0x341
github.com/alexandrevilain/controller-tools/pkg/reconciler.(*Reconciler).ReconcileBuilder.func1()
	/go/pkg/mod/github.com/alexandrevilain/controller-tools@v0.2.2/pkg/reconciler/reconciler.go:54 +0x2a
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc000db7560?, {{0xc000e49390?, 0x0?}, {0xc0007cec60?, 0x2c05c38?}}, {0x2c225a8, 0xc000db7560})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x2c05c38, 0xc000dcd680}, {0x2c12b00, 0xc0007405a0}, {0x2c225a8?, 0xc000db7560}, 0xc000f919e0?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/controller/controllerutil/controllerutil.go:211 +0x274
github.com/alexandrevilain/controller-tools/pkg/reconciler.(*Reconciler).ReconcileBuilder(0xc0002568c0, {0x2c05c38, 0xc000dcd680}, {0x2c21770?, 0xc000dc2900}, {0x2bed820?, 0xc0008c3820?})
	/go/pkg/mod/github.com/alexandrevilain/controller-tools@v0.2.2/pkg/reconciler/reconciler.go:53 +0x115
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalClusterReconciler).reconcileResources(0xc000256900, {0x2c05c38, 0xc000dcd680}, 0xc000dc2900)
	/workspace/controllers/temporalcluster_controller.go:153 +0xe5
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalClusterReconciler).Reconcile(0xc000256900, {0x2c05c38, 0xc000dcd680}, {{{0xc000bf038c?, 0x0?}, {0xc000bf03b8?, 0x40e027?}}})
	/workspace/controllers/temporalcluster_controller.go:143 +0x73a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2c05c38?, {0x2c05c38?, 0xc000dcd680?}, {{{0xc000bf038c?, 0x2231580?}, {0xc000bf03b8?, 0x2be7058?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00079c640, {0x2c05b90, 0xc000545450}, {0x23e7b40?, 0xc000775b60?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00079c640, {0x2c05b90, 0xc000545450})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:222 +0x587
```

**Comment by yujunz** [comment]
@alexandrevilain any quick hint about how to investigate such nil pointer error?

**Comment by yujunz** [comment]
```
    --- FAIL: TestPersistence/cassandra_persistence (260.92s)
```
Flake?

**Comment by yujunz** [comment]
It fails for different reasons

https://github.com/alexandrevilain/temporal-operator/actions/runs/6561180880/job/17824957625#step:9:316

```
=== RUN   TestPersistence/mysql_persistence/Temporal_cluster_can_handle_workflows_after_upgrade#01
    utils_test.go:293: Forwarding from 127.0.0.1:38519 -> 7233
    utils_test.go:293: Forwarding from [::1]:38519 -> 7233
    utils_test.go:360: Port forwarding is ready to get traffic.
    assert_test.go:89: Temporal frontend addr: localhost:38519
I1018 15:15:51.823619   15362 client.go:137]  "msg"="Connecting to temporal cluster" "address"="localhost:38519"
    utils_test.go:293: Handling connection for 38519
E1018 15:15:51.846575   15362 portforward.go:409] an error occurred forwarding 38519 -> 7233: error forwarding port 7233 to pod 8c45a34e4085849407e3f6274d15d9ed94e380be6facf4b2aeb1c444f061ee4e, uid : failed to execute portforward in network namespace "/var/run/netns/cni-b5d23b3d-29a3-a29b-5f23-b32c923b13ed": failed to connect to localhost:7233 inside namespace "8c45a34e4085849407e3f6274d15d9ed94e380be6facf4b2aeb1c444f061ee4e", IPv4: dial tcp4 127.0.0.1:7233: connect: connection refused IPv6 dial tcp6 [::1]:7233: connect: connection refused 
panic: lost connection to pod

goroutine 1674 [running]:
github.com/alexandrevilain/temporal-operator/tests/e2e.forwardPortToPod.func1()
	/home/runner/work/temporal-operator/temporal-operator/tests/e2e/utils_test.go:355 +0xa6
created by github.com/alexandrevilain/temporal-operator/tests/e2e.forwardPortToPod
	/home/runner/work/temporal-operator/temporal-operator/tests/e2e/utils_test.go:352 +0x358
FAIL	github.com/alexandrevilain/temporal-operator/tests/e2e	1327.990s
FAIL
make: *** [Makefile:100: test-e2e] Error 1
Error: Process completed with exit code 2.
```

**Review by alexandrevilain — APPROVED** [review]
Thanks for the addition!

**Pull request merged**
