### PR TITLE
Pass GOPROXY from host to docker build

### PR DESCRIPTION
**Pull request by yujunz**

### CODE REVIEW

**Review by alexandrevilain — APPROVED** [review]

**Comment by yujunz** [comment]
Are those e2e test failure just flaky or regression in main branch? I don't think GOPROXY will affect any functions.

**Comment by alexandrevilain** [comment]
Yes e2e are flaky for some days. I have to check why

**Comment by alexandrevilain** [comment]
This may be fixed by: https://github.com/alexandrevilain/temporal-operator/pull/527
I'm running some tests. If it works and I merge it, you'll have to rebase this PR, sorry for the inconvenience.

**Comment by alexandrevilain** [comment]
@yujunz Could you please rebase your PR ?
e2e tests where flaky due to storage issue which has been fixed in https://github.com/alexandrevilain/temporal-operator/pull/527 it's now merged on main branch.
Sorry for the inconvenience.

**Pull request merged**
